version: '3'

volumes:
  prometheus_data: {}

services:
  oncall:
    build: .
    container_name: oncall
    ports:
      - "8080:8080"
      - "8082:8082"
    environment:
      - DOCKER_DB_BOOTSTRAP=1
      - IRIS_API_HOST=iris
    volumes:
      - ./configs/config.docker.yaml:/home/oncall/config/config.yaml

  oncall-mysql:
    container_name: oncall-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234

  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - '9090:9090'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys/fs/cgroup/:/sys/fs/cgroup/
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8081:8080
    deploy:
      mode: global

  blackbox:
    image: prom/blackbox-exporter:v0.12.0
    command:
      - --config.file=/etc/blackbox/blackbox.yml
    volumes:
      - ./blackbox/blackbox.yml:/etc/blackbox/blackbox.yml
    ports:
      - 9115:9115
    depends_on:
      - prometheus

  my_metrics:
    build: my_metrics
    ports:
      - 5050:5050

